name: 'austin_animal_center'
version: '1.0.0'

profile: 'default'

model-paths: ["models"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  austin_animal_center:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table